"""parece que ya quedo

Revision ID: 437834ece070
Revises: a10a5b2fc553
Create Date: 2021-03-28 18:18:49.637352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437834ece070'
down_revision = 'a10a5b2fc553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tuxcoin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('void', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('postcoin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postcoin_id'], ['postcoin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tuxcoin_timestamp'), 'tuxcoin', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tuxcoin_timestamp'), table_name='tuxcoin')
    op.drop_table('tuxcoin')
    # ### end Alembic commands ###
