"""empty message

Revision ID: 806b3388f1c2
Revises: e9ea301832b1
Create Date: 2021-04-27 13:57:16.856707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806b3388f1c2'
down_revision = 'e9ea301832b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postcoin', sa.Column('alt', sa.Float(), nullable=True))
    op.add_column('tuxcoin', sa.Column('alt', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tuxcoin', 'alt')
    op.drop_column('postcoin', 'alt')
    # ### end Alembic commands ###
