"""Cambiar el code de Tuxcoin por token

Revision ID: c615961a2df3
Revises: 437834ece070
Create Date: 2021-04-02 22:26:31.926763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c615961a2df3'
down_revision = '437834ece070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postcoin', sa.Column('token', sa.String(length=256), nullable=True))
    op.drop_index('ix_postcoin_code', table_name='postcoin')
    op.create_index(op.f('ix_postcoin_token'), 'postcoin', ['token'], unique=True)
    op.drop_column('postcoin', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postcoin', sa.Column('code', mysql.VARCHAR(length=256), nullable=True))
    op.drop_index(op.f('ix_postcoin_token'), table_name='postcoin')
    op.create_index('ix_postcoin_code', 'postcoin', ['code'], unique=True)
    op.drop_column('postcoin', 'token')
    # ### end Alembic commands ###
