"""se agrego alt para altitud en los datos de gps

Revision ID: e9ea301832b1
Revises: c615961a2df3
Create Date: 2021-04-27 13:55:42.603634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ea301832b1'
down_revision = 'c615961a2df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postcoin', sa.Column('alt', sa.Float(), nullable=True))
    op.add_column('tuxcoin', sa.Column('alt', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tuxcoin', 'alt')
    op.drop_column('postcoin', 'alt')
    # ### end Alembic commands ###
