"""poniendo length a los campos de string

Revision ID: f83a19af41fb
Revises: e7fe067f13d3
Create Date: 2021-03-27 22:45:05.134470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83a19af41fb'
down_revision = 'e7fe067f13d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postcoin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('code', sa.String(length=256), nullable=True),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.Column('posted', sa.Boolean(), nullable=True),
    sa.Column('void', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_postcoin_code'), 'postcoin', ['code'], unique=True)
    op.create_index(op.f('ix_postcoin_timestamp'), 'postcoin', ['timestamp'], unique=False)
    op.create_table('tuxcoin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('void', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('postcoin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postcoin_id'], ['postcoin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tuxcoin_timestamp'), 'tuxcoin', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tuxcoin_timestamp'), table_name='tuxcoin')
    op.drop_table('tuxcoin')
    op.drop_index(op.f('ix_postcoin_timestamp'), table_name='postcoin')
    op.drop_index(op.f('ix_postcoin_code'), table_name='postcoin')
    op.drop_table('postcoin')
    # ### end Alembic commands ###
